sonar.projectKey=Ambiance
sonar.projectName=Ambiance
sonar.host.url=https://sonarqube.ambiance-ensitech.me
sonar.login=${SONAR_TOKEN}

# Optionnel selon ton projet :
# sonar.sources=src
# sonar.language=js
# sonar.sourceEncoding=UTF-8
sonar.branch.name=develop

# =============== SOURCES ================
sonar.sources=ambiance-front/src,ambiance-back/src
sonar.tests=ambiance-front/src,ambiance-back/src
sonar.exclusions=**/node_modules/**,**/*.module.ts,**/*.routing.ts,**/dist/**, **/environments/*.ts, **/*.spec.ts, **/*.test.ts

# =============== TESTS ================
sonar.test.inclusions=**/*.spec.ts

# =============== COVERAGE ================
#sonar.typescript.lcov.reportPaths=ambiance-front/coverage/ambiance-front-/lcov.info
#sonar.typescript.lcov.reportPaths=ambiance-back/coverage/lcov.info

# Général
sonar.sourceEncoding=UTF-8