sonar.projectKey=Ambiance
sonar.projectName=Ambiance
sonar.host.url=https://sonarqube.ambiance-ensitech.me
sonar.login=${SONAR_TOKEN}

# Optionnel selon ton projet :
# sonar.sources=src
# sonar.language=js
# sonar.sourceEncoding=UTF-8
sonar.branch.name=develop

# ===== FRONTEND (Angular) =====
sonar.sources=ambiance-front/src
sonar.tests=ambiance-front/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.module.ts,**/*.routing.ts
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info