sonar.projectKey=ambiance
sonar.projectName=ambiance
sonar.host.url=https://sonarqube.ambiance-ensitech.me
sonar.login=${SONAR_TOKEN}

# Optionnel selon ton projet :
# sonar.sources=src
# sonar.language=js
# sonar.sourceEncoding=UTF-8
